#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP my_c_rle(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"my_c_rle", (DL_FUNC) &my_c_rle, 1},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_myrle(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
